### ISSUE TITLE
Working with Lonsonho

### ISSUE THREAD

**Issue by Flipsoo** [SynAckFin/TuyOTA#10]
Hey, i wanted to update the wiki, but get an error i think because im new to GitHub in that way that i registered myself only to add this comment.
Got your TuyOTA working on the Lonsonho Smart Plug (https://www.aliexpress.com/item/Lonsonho-Smart-Plug-Wifi-Smart-Socket-Power-Monitor-EU-France-US-AU-UK-Korea-Plug-Outlet/32901221191.html?spm=a2g0s.9042311.0.0.27424c4ddsotkv) 

works like charm (switch and power monitoring works with the Tasmota BlitzWolf build)  only inbuilt rgb led won't work=)

**Comment by Flipsoo** [comment]
> Hey, i wanted to update the wiki, but get an error i think because im new to GitHub in that way that i registered myself only to add this comment.
> Got your TuyOTA working on the Lonsonho Smart Plug (https://www.aliexpress.com/item/Lonsonho-Smart-Plug-Wifi-Smart-Socket-Power-Monitor-EU-France-US-AU-UK-Korea-Plug-Outlet/32901221191.html?spm=a2g0s.9042311.0.0.27424c4ddsotkv)
> 
> works like charm (switch and power monitoring works with the Tasmota BlitzWolf build) only inbuilt rgb led won't work=)

--> and know im flagged in GitHub, that's a good start:D

**Comment by erwill2** [comment]
Added to Wiki for you!

**Comment by Flipsoo** [comment]
Thanks a lot 🤗☺️
