### ISSUE TITLE
Error running the script

### ISSUE THREAD

**Issue by damondins** [SynAckFin/TuyOTA#13]
I was running the tuyamockcloud and was able to move over a device but then after a reboot I get this from the TuyOTA script.

Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...

**Comment by SynAckFin** [comment]
If you have installed a new firmware with the tuyamockcloud I dont see what the problem is with this.

**Comment by damondins** [comment]
It is no longer setting up so that I can do the other devices I am still working to get moved to tasmota. It just exits

**Comment by SynAckFin** [comment]
Did you run the ./stop_flash.sh script in tuyamockcloud because they configure and run all sorts of services.

**Comment by damondins** [comment]
Its back up and functioning. Something was just hung up it seems
