### ISSUE TITLE
After flashing the device does not respond

### ISSUE THREAD

**Issue by lyolic** [SynAckFin/TuyOTA#19]
A have flashed the following device SESOO WIFI-SK3

> pi@rasp:~/TuyOTA`
> 
>  $ sudo ./tuyota.pl -ip 192.168.1.76 -s Network -p password
> Stage One firmware not found, downloading it
> --2019-02-17 00:24:29--  https://github.com/SynAckFin/TuyOTA/raw/master/static/image_user2-0x81000.bin
> Resolving github.com (github.com)... 140.82.118.4, 140.82.118.3
> Connecting to github.com (github.com)|140.82.118.4|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/image_user2-0x81000.bin [following]
> --2019-02-17 00:24:29--  https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/image_user2-0x81000.bin
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.244.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.244.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 239220 (234K) [application/octet-stream]
> Saving to: ‘image_user2-0x81000.bin’
> 
> image_user2-0x81000.bin                   100%[=====================================================================================>] 233.61K  --.-KB/s    in 0.1s
> 
> 2019-02-17 00:24:30 (2.09 MB/s) - ‘image_user2-0x81000.bin’ saved [239220/239220]
> 
> Stage Two firmware not found, downloading it
> --2019-02-17 00:24:30--  https://github.com/SynAckFin/TuyOTA/raw/master/static/sonoff.bin
> Resolving github.com (github.com)... 140.82.118.3, 140.82.118.4
> Connecting to github.com (github.com)|140.82.118.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/sonoff.bin [following]
> --2019-02-17 00:24:30--  https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/sonoff.bin
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 482512 (471K) [application/octet-stream]
> Saving to: ‘sonoff.bin’
> 
> sonoff.bin                                100%[=====================================================================================>] 471.20K  2.97MB/s    in 0.2s
> 
> 2019-02-17 00:24:31 (2.97 MB/s) - ‘sonoff.bin’ saved [482512/482512]
> 
> Getting interface into stable state
> RTNETLINK answers: Cannot assign requested address
> RTNETLINK answers: Cannot assign requested address
> Done
> Using WiFi device wlan0 for Access Point
> Creating Access Point config file hostapd.conf
> Starting Access Point with SSID ZAGDU-789
> Giving Access Point IP address 10.44.57.1, pid is 7330
> Redirecting device 192.168.1.76 to use Access Point ZAGDU-789
> **** New device detected. ID: XXXXXXXXXXXXXXXXXXX IP:192.168.1.76
> Asking device to move networks and upgrade...
> Redirecting device 192.168.1.76 to use Access Point ZAGDU-789
> **** Redirect appears successful
> DHCP Discover 80:7d:3a:5c:23:19 10.44.57.67
> DHCP Request 80:7d:3a:5c:23:19 10.44.57.67
> **** Device XXXXXXXXXXXXXXXXXX has changed IP from 192.168.1.76 to 10.44.57.67
> Received DNS query for mq.gw.tuyaeu.com.
> Sending 10.44.57.1 as response
> Accepting MQTT connection, forwarding to mq.gw.tuyaeu.com.
> Received DNS query for a.tuyaeu.com.
> Sending 10.44.57.1 as response
> Receiving www request
> Fetching Request Content
> URL: /gw.json?a=atop.online.debug.log
> Response: HTTP/1.1 200 OK
> {"result":true,"t":1550352292,"e":false,"success":true}
> Receiving www request
> URL: /gw.json?a=tuya.device.dynamic.config.get
> Response: HTTP/1.1 200 OK
> {"result":{"validTime":1800,"time":1550352292,"config":{}},"t":1550352292,"e":false,"success":true}
> Receiving www request
> Fetching Request Content
> URL: /gw.json?a=tuya.device.upgrade.silent.get
> Sent upgrade response
> Receiving www request
> Fetching Request Content
> URL: /gw.json?a=s.gw.upgrade.updatestatus
> Response: HTTP/1.1 200 OK
> {"t":1550352312,"e":false,"success":true}
> Received DNS query for fakewebsite.
> Sending 10.44.57.1 as response
> Receiving www request
> Sending firmware image_user2-0x81000.bin
> Receiving www request
> Sending firmware image_user2-0x81000.bin
> Sending bytes 239271-478490 from offset 0
> DHCP Discover 80:7d:3a:5c:23:19 10.44.57.67
> DHCP Request 80:7d:3a:5c:23:19 10.44.57.67
> Shutting down...
> Setting up IP Address 192.168.4.2 for Final Stages
> Getting interface into stable state
> RTNETLINK answers: Cannot assign requested address
> Done
> Setting up wifi scan
> Setting up listener for FinalStage
> ***** FinalStage Detected ******
> ***** Connected to FinalStage ******
> ***** Receiving FinalStage Request ****
> REQ: Client closed connection while receiving request:
> ***** Receiving FinalStage Request ****
> Sending firmware sonoff.bin
> ***** Tasmota Firmware sent to device ******
> ***** Found Sonoff AP sonoff-0793 ******
> ***** Connected to sonoff-0793 ******
> Sending config to sonoff-0793
> ***** Config sent *****
> ***** Found Sonoff AP sonoff-0793 ******
> ***** Connected to sonoff-0793 ******
> Failed to connect to device sonoff-0793: No route to host
> Shutting down...
> Getting interface into stable state
> RTNETLINK answers: Cannot assign requested address
> Done
> Finished
> Exiting....
> Shutting down...` 

But unfortunatly, after flashing the device does not respond at all. Are their any chances to reanimate it?

**Comment by SynAckFin** [comment]
From the logs it looks like like the device was successfully flashed.

Use your phones WiFi and connect to an access point called sonoff-0793. Then open the phones browser and type in the address 192.168.4.1
That should connect you to the device and you can then configure it with your WiFi name and password.

**Comment by lyolic** [comment]
Thank you for your reply. Unfortunately I don't see any access points named sonoff-xxxx :(

**Comment by SynAckFin** [comment]
Don't worry we can probably get your device back.

The command line you used in the log is:
```
$ sudo ./tuyota.pl -ip 192.168.1.76 -s Network -p password
```
Is this the command line you used or did you specify your own WiFi name and password for -s and -p?
If you used your own WiFi name and password then did you put the correct ones in?
If you did put the correct ones in then does your WiFi name or password have any non-alphanumeric characters in them?
I see you are using a Pi, is it a Pi3 and are you using the built-in WiFi?

**Comment by lyolic** [comment]
You are magician :) I've used wrong case in letter of wifi name. Now web access is working and I have to understand right configuration :)

**Comment by SynAckFin** [comment]
Glad I could help.
