### ISSUE TITLE
Elegiant Single Plug

### ISSUE THREAD

**Issue by jnalley20** [SynAckFin/TuyOTA#7]
I think I just bricked two of these.
https://www.amazon.com/gp/product/B07B9XCY5M/ref=ppx_yo_dt_b_asin_title_o08__o00_s00?ie=UTF8&psc=1

Fresh Pi, terminal copy below.
login as: pi
pi@192.168.88.216's password:
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Nov 13 08:24:54 2018
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
pi@raspberrypi:~ $ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt install hostapd
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libnl-route-3-200
The following NEW packages will be installed:
  hostapd libnl-route-3-200
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 576 kB of archives.
After this operation, 1,565 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirror.us.leaseweb.net/raspbian/raspbian stretch/main armhf libnl-route-3-200 armhf 3.2.27-2 [113 kB]
Get:2 http://mirror.us.leaseweb.net/raspbian/raspbian stretch/main armhf hostapd armhf 2:2.4-1+deb9u2 [463 kB]
Fetched 576 kB in 1s (384 kB/s)
Selecting previously unselected package libnl-route-3-200:armhf.
(Reading database ... 133377 files and directories currently installed.)
Preparing to unpack .../libnl-route-3-200_3.2.27-2_armhf.deb ...
Unpacking libnl-route-3-200:armhf (3.2.27-2) ...
Selecting previously unselected package hostapd.
Preparing to unpack .../hostapd_2%3a2.4-1+deb9u2_armhf.deb ...
Unpacking hostapd (2:2.4-1+deb9u2) ...
Setting up libnl-route-3-200:armhf (3.2.27-2) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u8) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up hostapd (2:2.4-1+deb9u2) ...
Processing triggers for systemd (232-25+deb9u8) ...
pi@raspberrypi:~ $ sudo sed -i '3idenyinterfaces wlan0' /etc/dhcpcd.conf
pi@raspberrypi:~ $ head -3 /etc/dhcpcd.conf
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.
denyinterfaces wlan0
pi@raspberrypi:~ $ ps -fu root | grep wpa_supplicant
root       371     1  0 15:56 ?        00:00:00 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0 -Dnl80211,wext
pi@raspberrypi:~ $ sudo systemctl restart dhcpcd
pi@raspberrypi:~ $ ps -fu root | grep wpa_supplicant
pi@raspberrypi:~ $ git clone https://github.com/SynAckFin/TuyOTA
Cloning into 'TuyOTA'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 20 (delta 6), reused 11 (delta 3), pack-reused 0
Unpacking objects: 100% (20/20), done.
pi@raspberrypi:~ $ cd TuyOTA
pi@raspberrypi:~/TuyOTA $ ls
LICENSE  README.md  static  tuyota.pl
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -ip 192.168.99.80 -s IoT -p Nal
Stage One firmware not found, downloading it
--2019-01-18 16:04:33--  https://github.com/SynAckFin/TuyOTA/raw/master/static/image_user2-0x81000.bin
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/image_user2-0x81000.bin [following]
--2019-01-18 16:04:33--  https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/image_user2-0x81000.bin
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 239220 (234K) [application/octet-stream]
Saving to: ‘image_user2-0x81000.bin’

image_user2-0x81000.bin          100%[========================================================>] 233.61K  --.-KB/s    in 0.1s

2019-01-18 16:04:33 (2.05 MB/s) - ‘image_user2-0x81000.bin’ saved [239220/239220]

Stage Two firmware not found, downloading it
--2019-01-18 16:04:34--  https://github.com/SynAckFin/TuyOTA/raw/master/static/sonoff.bin
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/sonoff.bin [following]
--2019-01-18 16:04:34--  https://raw.githubusercontent.com/SynAckFin/TuyOTA/master/static/sonoff.bin
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 482512 (471K) [application/octet-stream]
Saving to: ‘sonoff.bin’

sonoff.bin                       100%[========================================================>] 471.20K  --.-KB/s    in 0.1s

2019-01-18 16:04:34 (3.41 MB/s) - ‘sonoff.bin’ saved [482512/482512]

Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Creating Access Point config file hostapd.conf
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1271
Redirecting device 192.168.99.80 to use Access Point ZAGDU-789
**** Redirect appears successful
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.71
DHCP Request b4:e6:2d:17:6d:21 10.44.57.71
**** New device detected. ID: 04200489b4e62d176d21 IP:10.44.57.71
**** New device looks to be part way through upgrading
**** Forcing it to retry the upgrade
Redirecting device 10.44.57.71 to use Access Point ZAGDU-789
**** Redirect appears successful
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.71
DHCP Request b4:e6:2d:17:6d:21 10.44.57.71
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Accepting MQTT connection, forwarding to mq.gw.tuyaus.com.
Received DNS query for a.tuyaus.com.
Sending 10.44.57.1 as response
Receiving www request
Fetching Request Content
URL: /gw.json?a=atop.online.debug.log
Unable to reach a.tuyaus.com: Connection refused at ./tuyota.pl line 720, <$fh> line 15.
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -ip 192.168.99.80 -s IoT -p NalPass
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1292
Redirecting device 192.168.99.80 to use Access Point ZAGDU-789
Unable to open socket to 192.168.99.80: Connection timed out
The device might be at the next stage, ignoring for now
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.97
DHCP Request c8:f6:50:ba:1b:e0
c8:f6:50:ba:1b:e0: Unknown host
Bad arg length for Socket::pack_sockaddr_in, length is 0, should be 4 at /usr/lib/arm-linux-gnueabihf/perl/5.24/Socket.pm line 157, <$fh> line 1.
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -ip 192.168.99.80 -s IoT -p NalPass
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1324
Redirecting device 192.168.99.80 to use Access Point ZAGDU-789
Unable to open socket to 192.168.99.80: Connection timed out
The device might be at the next stage, ignoring for now
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Discover b4:e6:2d:17:6d:21 10.44.57.66
DHCP Request b4:e6:2d:17:6d:21 10.44.57.66
**** New device detected. ID: 04200489b4e62d176d21 IP:10.44.57.66
**** New device looks to be part way through upgrading
**** Forcing it to retry the upgrade
Redirecting device 10.44.57.66 to use Access Point ZAGDU-789
Unable to open socket to 10.44.57.66: Connection refused
The device might be at the next stage, ignoring for now
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Received DNS query for a.tuyaus.com.
Sending 10.44.57.1 as response
Accepting MQTT connection, forwarding to mq.gw.tuyaus.com.
Receiving www request
URL: /gw.json?a=tuya.device.upgrade.silent.get
Sent upgrade response
Receiving www request
Fetching Request Content
URL: /gw.json?a=s.gw.upgrade.updatestatus
Response: HTTP/1.1 200 OK
Received DNS query for fakewebsite.
Sending 10.44.57.1 as response
Receiving www request
Sending firmware image_user2-0x81000.bin
Receiving www request
Sending firmware image_user2-0x81000.bin
Sending bytes 51-239270 from offset 0
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -ip 192.168.99.80
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1414
Redirecting device 192.168.99.80 to use Access Point ZAGDU-789
Unable to open socket to 192.168.99.80: Connection timed out
The device might be at the next stage, ignoring for now
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -s IoT -p NalPass
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1484
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $
login as: pi
pi@192.168.88.216's password:
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Jan 18 15:56:30 2019 from 192.168.88.150
pi@raspberrypi:~ $ ls
Desktop  Documents  Downloads  MagPi  Music  Pictures  Public  Templates  TuyOTA  Videos
pi@raspberrypi:~ $ cd TuyOTA/
pi@raspberrypi:~/TuyOTA $ ;s
-bash: syntax error near unexpected token `;'
pi@raspberrypi:~/TuyOTA $ ls
hostapd.conf  image_user2-0x81000.bin  LICENSE  README.md  sonoff.bin  static  tuyota.pl
pi@raspberrypi:~/TuyOTA $ sudo nano hostapd.conf
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -s IoT -p NalPass
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 824
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 865
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -ip 192.168.99.80 -s IoT -p NalPass
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 919
Redirecting device 192.168.99.80 to use Access Point ZAGDU-789
Unable to open socket to 192.168.99.80: Connection timed out
The device might be at the next stage, ignoring for now
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo nano hostapd.conf
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -s IoT -p NalPass
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 982
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -ip 192.168.99.82
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1067
Redirecting device 192.168.99.82 to use Access Point ZAGDU-789
**** Redirect appears successful
DHCP Discover ec:fa:bc:86:89:d4 10.44.57.208
DHCP Request ec:fa:bc:86:89:d4 10.44.57.208
**** New device detected. ID: 02200194ecfabc8689d4 IP:10.44.57.208
**** New device looks to be part way through upgrading
**** Forcing it to retry the upgrade
Redirecting device 10.44.57.208 to use Access Point ZAGDU-789
**** Redirect appears successful
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
DHCP Discover ec:fa:bc:86:89:d4 10.44.57.208
DHCP Request ec:fa:bc:86:89:d4 10.44.57.208
Received DNS query for mq.gw.tuyaus.com.
Sending 10.44.57.1 as response
Accepting MQTT connection, forwarding to mq.gw.tuyaus.com.
Received DNS query for a.tuyaus.com.
Sending 10.44.57.1 as response
Receiving www request
Fetching Request Content
URL: /gw.json?a=atop.online.debug.log
Response: HTTP/1.1 200 OK
Receiving www request
URL: /gw.json?a=tuya.device.dynamic.config.get
Response: HTTP/1.1 200 OK
Receiving www request
Fetching Request Content
URL: /gw.json?a=tuya.device.upgrade.silent.get
Sent upgrade response
Receiving www request
Fetching Request Content
URL: /gw.json?a=s.gw.upgrade.updatestatus
Response: HTTP/1.1 200 OK
Received DNS query for fakewebsite.
Sending 10.44.57.1 as response
Receiving www request
Sending firmware image_user2-0x81000.bin
Receiving www request
Sending firmware image_user2-0x81000.bin
Sending bytes 51-239270 from offset 0
DHCP Request 00:18:dd:04:aa:0b
00:18:dd:04:aa:0b: Unknown host
Bad arg length for Socket::pack_sockaddr_in, length is 0, should be 4 at /usr/lib/arm-linux-gnueabihf/perl/5.24/Socket.pm line 157, <$fh> line 27.
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1089
Shutting down...
Setting up IP Address 192.168.4.2 for Final Stages
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Setting up wifi scan
Setting up listener for FinalStage
Shutting down...
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Finished
Exiting....
Shutting down...
pi@raspberrypi:~/TuyOTA $

**Comment by erwill2** [comment]
I have one that Looks like this. I get blue light on startup and red when I hit the button. No wifi or anything reported. Will have to manually flash.

**Comment by SynAckFin** [comment]
It look like your device has the interim firmware on there so it is't a brick just yet.
To confirm this turn the device on and use your phone's WiFi to search for access points. If you see one called "FinalStage" then your device has the interim firmware installed, if you see any called "Sonoff-XXXX" where X is a number then connect your phone to it, open a browser and connect to http://192.168.4.1/ and fill in the form.

If it is at the final stage then there might be something running on your pi stopping the WiFi link from detecting and connecting to access points. This will probably be wpa_supplicant so run the following:

`ps -fC wpa_supplicant`

If it lists any processes then kill them and then run the script again.

For example:

```
raspberrypi-431 $ ps -fC wpa_supplicant
UID        PID  PPID  C STIME TTY          TIME CMD
root       413     1  0 Jan18 ?        00:00:00 wpa_supplicant -B -c/etc/wpa_sup
root       541     1  0 Jan18 ?        00:00:00 /sbin/wpa_supplicant -u -s -O /r
raspberrypi-432 $ sudo kill 413 541
raspberrypi-433 $ ps -fC wpa_supplicant
UID        PID  PPID  C STIME TTY          TIME CMD
raspberrypi-434 $ 
```
If you reboot then you will have to kill the processes again before running the script.

**Comment by jnalley20** [comment]
No wifi broadcast from the devices.  No results when I, ps -fu root | grep wpa_supplicant.  Or ps -fC wpa_supplicant

**Comment by SynAckFin** [comment]
Try the following commands:
```
ip link set wlan0 down
iwconfig wlan0 mode monitor
ip link set wlan0 up

```
If the above didn't produce any errors then run the following:
`tcpdump -e -i wlan0 -s0 ether host b4:e6:2d:17:6d:21
`
and then power the device on and see if there is any output.
Note: This will not work with the built-in WiFi device on a Pi 3.

**Comment by jnalley20** [comment]
Awesome because I'm using a Pi3.  And the first trash laptop I grabbed to put linux on also has an unsupported card....  I've got a few more options but it will take some time.

sudo iwconfig wlan0 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Operation not supported.

**Comment by jnalley20** [comment]
I wasn't able to get a linux rig with wifi up but I did run Acrylic Wifi on my windows machine to monitor wifi activity and it didn't pick anything up.

**Comment by jnalley20** [comment]
Update.  I had a few more of those switches and gave the https://github.com/ct-Open-Source/tuya-convert solution a try.  It worked 6 times on this Tuya switch.  Now I'm going to try two other models that I have.  Thank you for your contribution @SynAckFin .

**Comment by jnalley20** [comment]
> I have one that Looks like this. I get blue light on startup and red when I hit the button. No wifi or anything reported. Will have to manually flash. Is the model number AWP04L?

I purchased 8 of these and I noticed that 3 of them had different model numbers.  3 where AWP04L's.

**Comment by jnalley20** [comment]
And here is the module to enable power monitoring support in Tasmota.  I've requested that it be added.

{ "Tuya Smart Plug1", // Tuya S01 or AWP04L with Energy Monitoring
//https://www.amazon.com/gp/product/B07B9XCY5M/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1
GPIO_LED2_INV, // GPIO00 Red Led (1 = On, 0 = Off)
0, 0,
GPIO_NRG_SEL_INV, // GPI03 BL0937 or HJL-01 Sel output (0 = Voltage)
0, // GPIO04
GPIO_HJL_CF, // GPIO05 BL0937 or HJL-01 CF power
0, 0, 0, 0, 0, 0, // Flash connection
GPIO_REL1, // GPIO12 Relay (0 = Off, 1 = On)
GPIO_KEY1, // GPIO13 Button
GPIO_NRG_CF1, // GPIO14 BL0937 or HJL-01 CF1 current / voltage
GPIO_LED1_INV, // GPIO15 LED Blue
0, 0
}
